VPN up and down scripts

diff --git a/bin/vpn-up b/bin/vpn-up
--- a/bin/vpn-up
+++ b/bin/vpn-up
@@ -2,12 +2,87 @@
 #
 # Connect to the VPN at ${VPN_ENDPOINT}.
 
-if [[ -z ${VPN_ENDPOINT} ]]; then
-  echo "Please define \${VPN_ENDPOINT} in ${HOME}/.localrc."
+[ -z "${VPN_ENDPOINT}" ] && {
+  echo "Please define \${VPN_ENDPOINT} in ${HOME}/.localrc." >&2
   exit 1
+}
+
+[ -z "${GATEWAY}" ] && {
+  echo "Please define \${GATEWAY} in ${HOME}/.localrc." >&2
+  exit 1
+}
+
+[ -z "${FQDNS}" ] && {
+  echo "Please define \${FQDNS} in ${HOME}/.localrc." >&2
+  exit 1
+}
+
+# Prompt for password at beginning
+sudo echo
+
+if [[ ! -e /etc/resolv.conf.vpn-up.bak ]]
+then
+    echo "Backing up /etc/resolv.conf..."
+    sudo cp /etc/resolv.conf{,.vpn-up.bak}
+else
+    echo "/etc/resolv.conf already backed up; skipping"
+fi
+if [[ ! -e /etc/hosts.vpn-up.bak ]]
+then
+    echo "Backing up /etc/hosts..."
+    sudo cp /etc/hosts{,.vpn-up.bak}
+else
+    echo "/etc/hosts already backed up; skipping"
 fi
 
-sudo openconnect -s /etc/vpnc/vpnc-script \
-  --pid-file=/var/vpn/connection.pid \
+sudo openconnect $VPN_ENDPOINT \
+  --background \
+  --pid-file=${HOME}/.openconnect.pid
+
+vpn_if='tun0'
+while true ; do
+    ifconfig utun0 > /dev/null 2>&1
+    if [ $? -eq 0 ] ; then
+        break
+    fi
+    echo "Waiting for utun0 to appear..."
+    sleep 1
+done
+
+echo "Preparing to update DNS and routes..."
+sleep 5
+
+echo "Add google's nameserver as preferred..."
+sudo sed -i .bak -e "/nameserver 8.8.8.8/d" /etc/resolv.conf
+sudo sed -i -e '1 i\
+nameserver 8.8.8.8
+' /etc/resolv.conf
+
+echo "Set default and 10 routes..."
+sudo route change default $GATEWAY
+sudo route -nv add -net 10 -interface utun0
+
+echo "# Generated by vpn-up script
+127.0.0.1        localhost
+255.255.255.255  broadcasthost
+::1              localhost" | sudo tee /etc/hosts
+
+for i in $FQDNS;
+do
+    IP=$(dig $i +short)
+    if [[ -n $IP ]]
+    then
+        echo "Setting route and host entry: $i -> $IP..."
+        sudo route -nv add $IP -interface utun0
+        echo "$IP  $i" | sudo tee -a /etc/hosts
+    else
+        echo "Could not resolve $i; skipping"
+    fi
+done
+
+exit 0
+
+sudo openconnect \
+  --pid-file=${HOME}/.openconnect.pid \
   --background \
   ${VPN_ENDPOINT}
